### ISSUE TITLE
Invalid name: "Technobabble Ipsum"

### ISSUE THREAD

**Issue by trailsandtribulations** [lawren/atom-technobabble#2]
when attempting to add to atom, got npm error Invalid Name.

see npm issue 7719.

**Comment by yellottyellott** [comment]
bump

**Comment by bordomat** [comment]
Same here!

![voila_capture 2015-08-06_10-55-31_dop](https://cloud.githubusercontent.com/assets/1638738/9107802/71b399f8-3c2a-11e5-9643-e96ab5d688fe.png)

**Comment by chrisdubya** [comment]
bumppp

**Comment by lawren** [comment]
It has to be installed as technobabble-ipsum. I have updated the readme to make it less confusing.
