### ISSUE TITLE
Provide as npm module

### ISSUE THREAD

**Issue by RangerMauve** [lawren/atom-technobabble#3]
I really like the idea of the technobabble generation. Would you consider creating a separate npm module for just the generation?

**Comment by lawren** [comment]
Do you mean something like this? http://lawrenwhitehead.com/technobabble

**Comment by RangerMauve** [comment]
That's really cool, but I was thinking more like

`npm install technobabble`

```js
var babble = require("technobabble");

babble({paragraphs: 2});
```

**Comment by lawren** [comment]
Oh, I gotcha! That sounds like a pretty good idea. I'll see about throwing something together later this week...

**Comment by lawren** [comment]
I am working on this now. It's not entirely done, but sentence generation works decently well currently. Have at it and feel free to make any suggestions/PR's/Issues!

**Comment by RangerMauve** [comment]
Cool! I'll look later tonight. :D
