### ISSUE TITLE
Can not install packages

### ISSUE THREAD

**Issue by bordomat** [lawren/atom-technobabble#4]
Hi, I can not install Technobabble Ipsum. Screen shot attached.

Thx. 

M

![voila_capture 2015-08-06_10-55-31_dop](https://cloud.githubusercontent.com/assets/1638738/9107696/b02402f0-3c29-11e5-8811-7ad33164314d.png)

**Comment by lawren** [comment]
It has to be installed as technobabble-ipsum. I have updated the readme to make it less confusing.
